### ISSUE TITLE
Improve Imports

### ISSUE THREAD

**Issue by thirmprotocol** [MainframeHQ/mainframe-lending-protocol#1]
I guess the code is not written for the production, please mention it in readme or use proper release tags

**Comment by PaulRBerg** [comment]
This is a WIP. It's subject to being completely overhauled prior to the official release.

Thank you for your feedback.

**Comment by thirmprotocol** [comment]
Oh that makes sense !

**Comment by paulrberg** [comment]
Hey @ghost, lots of things changed since you opened this issue.

We now have a thorough documentation for the Hifi protocol, available at [docs.hifi.finance](https://docs.hifi.finance/). There is information there for how to use the [@hifi/protocol](https://www.npmjs.com/package/@hifi/protocol) package, which can be installed via npm/ yarn and later imported in your Solidity project.
